"""
agent/state.py

GiftAgentState — the single shared state object for the entire LangGraph workflow.

Design principles:
- Every field has a clear purpose documented inline.
- Fields are never deleted — only appended/updated as the graph progresses.
- The state is serializable to JSON for persistence via MemorySaver.
- LLM nodes can read all fields but may only write to their designated output fields.
- Confidence scores (in scored_products) are computed deterministically before
  LLM nodes run; LLM nodes receive them as read-only context.
"""

from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict


class GiftAgentState(TypedDict, total=False):
    # ── THREAD IDENTITY ─────────────────────────────────────────────────────
    thread_id: str
    # Unique identifier for this workflow run. Set by ingest node.
    # Used by MemorySaver for state persistence and by artifact_store.

    # ── NODE 1: ingest ───────────────────────────────────────────────────────
    contact: dict
    # The raw contact dict after Pydantic validation and normalization.
    # Keys: name, role, company, location, linkedin_profile,
    #       relationship_context, gift_context
    # Never mutated after ingest.

    relationship_type: str
    # Extracted from contact.relationship_context.relationship_type.
    # Stored at top level for easy access by score_products.
    # Values: prospective_customer | existing_customer | colleague |
    #         executive | founder | partner | unknown

    profile_text: str
    # Flattened plaintext version of the LinkedIn profile.
    # Constructed by ContactInput.to_profile_text() in ingest node.
    # Passed to extract_and_query LLM as the source document.

    # ── NODE 2: extract_and_query (LLM #1) ──────────────────────────────────
    evidence_map: dict
    # {signal_text: [exact_quote_1, exact_quote_2, ...]}
    # Every signal must be supported by at least one exact quote
    # from the profile text. Used to enforce grounding in rank_gifts
    # and generate_messages. Built by LLM #1.

    strong_signals: list
    # Signals directly and explicitly stated in the profile.
    # Each item is a string describing one signal.

    weak_signals: list
    # Signals inferred with lower confidence.
    # Each item is a string describing one signal.

    queries: list
    # List of search query dicts:
    # [{query: str, type: "strong"|"weak"|"fallback", signal_used: str}]
    # Each query includes budget range and country in its text.
    # Generated by the same LLM #1 call as signals.

    # ── NODE 3: filter_signals ───────────────────────────────────────────────
    safe_signals: dict
    # {strong: [str], weak: [str], borderline: [str]}
    # Signals that passed the safety blocklist check.
    # Borderline signals are kept but flagged.

    signals_to_avoid: list
    # [{signal: str, reason: str, category: str}] for dropped signals,
    # plus the standard guardrail note.
    # Appears verbatim in final output.

    # ── NODE 4: search_products ──────────────────────────────────────────────
    raw_results: list
    # [{title, url, snippet, query_source, query_type}]
    # Raw DuckDuckGo results. Deduped by URL. Max 15 total.

    # ── NODE 5: validate_products ────────────────────────────────────────────
    validated_products: list
    # [{title, url, snippet, query_source, query_type,
    #   validation_report: {rule_name: {passed, weight, value, note}},
    #   validation_score: float,
    #   validation_tier: "pass"|"partial"|"fail",
    #   extracted_price: float|None,
    #   extracted_price_str: str|None,
    #   store: str}]
    # All products with their validation reports.
    # Only "pass" and "partial" tier products advance to scoring.

    # ── RETRY / ESCALATION ───────────────────────────────────────────────────
    retry_count: int
    # Number of times retry_widen has been triggered. Max 2.

    widened_budget_max: Optional[float]
    # Budget max after widening (budget_max * 1.10 per retry).
    # Used in retry queries instead of original budget.

    escalation_flag: bool
    # True if we ran out of retries and had to use partial-pass products.

    escalation_notes: str
    # Human-readable explanation of escalation: what failed and why.
    # Shown in human_review UI and included in final output.

    # ── NODE 6: score_products ───────────────────────────────────────────────
    scored_products: list
    # [{...validated_product,
    #   scores: {signal_score, budget_score, country_score,
    #            search_quality_score, relationship_score},
    #   confidence: float,     # DETERMINISTIC — LLMs cannot change this
    #   risk_level: str}]      # low|medium|high — derived from confidence
    # Sorted by confidence descending before ranking LLM receives it.

    # ── NODE 7: rank_gifts (LLM #2) ─────────────────────────────────────────
    ranked_gifts: list
    # Top 3 gifts selected by LLM from scored_products.
    # [{rank, gift_name, product_url, store, estimated_price,
    #   why_this_gift, personalisation_reasoning, evidence_citations,
    #   assumptions, confidence, risk_level}]
    # product_url is COPIED from scored_products — never LLM-constructed.
    # confidence is COPIED from scored_products — never LLM-generated.

    # ── NODE 8: generate_messages (LLM #3) ──────────────────────────────────
    final_recommendations: dict
    # Complete output matching the assignment schema.
    # Built after generate_messages adds personalised_message to each gift.

    # ── HUMAN REVIEW ────────────────────────────────────────────────────────
    review_history: list
    # [{action, reason, notes, gifts_flagged, timestamp}]
    # Persisted across regenerations. Passed to rank_gifts LLM so it
    # reads rejection reasons and avoids previously flagged products.

    review_action: str
    # Current action from reviewer: approve | reject | edit | regenerate
    # Set when human_review node resumes after interrupt.

    review_notes: str
    # Free-text notes from reviewer accompanying their action.

    edit_payload: Optional[dict]
    # For "edit" action: contains the inline edits to apply.
    # {gift_index: int, field: str, new_value: str}

    # ── OBSERVABILITY ────────────────────────────────────────────────────────
    logs: dict
    # {node_name: {start_time, end_time, latency_ms, tokens_used,
    #              llm_calls, errors: [str]}}
    # Each node writes its own entry. Aggregated in the done node.
