"""
models/products.py

Pydantic models for products at each stage of the pipeline:
  RawProduct     — directly from DuckDuckGo search results
  ValidationRule — result of a single validation check
  ValidatedProduct — product with full validation report + weighted score
  ProductScores  — breakdown of the confidence sub-scores
  ScoredProduct  — product with final deterministic confidence score
"""

from __future__ import annotations

from typing import Optional
from pydantic import BaseModel, Field


class RawProduct(BaseModel):
    """
    A single search result as returned by DuckDuckGo.
    The URL here is real — from the search engine, not generated by an LLM.
    """
    title: str = ""
    url: str = ""
    snippet: str = ""
    query_source: str = ""   # the exact query string that returned this result
    query_type: str = ""     # strong | weak | fallback


class ValidationRule(BaseModel):
    """Result of a single validation rule check."""
    passed: bool
    weight: float           # contribution to validation_score if passed
    value: Optional[str] = None   # extracted value (e.g. price string, domain)
    note: str = ""


class ValidatedProduct(BaseModel):
    """
    Product after the validate_products node.
    Contains the full validation report for auditability.
    validation_score is the weighted sum of passed rules (0.0–1.0).
    validation_tier categorizes the product for routing decisions.
    """
    title: str = ""
    url: str = ""
    snippet: str = ""
    query_source: str = ""
    query_type: str = ""

    validation_report: dict[str, ValidationRule] = Field(default_factory=dict)
    validation_score: float = 0.0
    validation_tier: str = "fail"  # pass | partial | fail

    extracted_price: Optional[float] = None
    extracted_price_str: Optional[str] = None
    store: str = ""   # inferred from domain (e.g. "Amazon.in", "Flipkart")


class ProductScores(BaseModel):
    """
    Breakdown of sub-scores used to compute confidence.
    All values are between 0.0 and 1.0.
    These are purely deterministic — computed from validation data,
    not generated by any LLM.
    """
    signal_score: float = 0.0       # weight: 0.35
    budget_score: float = 0.0       # weight: 0.25
    country_score: float = 0.0      # weight: 0.20
    search_quality_score: float = 0.0  # weight: 0.10
    relationship_score: float = 0.0    # weight: 0.10


# Confidence weight constants — single source of truth
CONFIDENCE_WEIGHTS = {
    "signal": 0.35,
    "budget": 0.25,
    "country": 0.20,
    "search_quality": 0.10,
    "relationship": 0.10,
}


class ScoredProduct(BaseModel):
    """
    Product with final confidence score after score_products node.
    The confidence value is deterministic and cannot be modified by LLMs.
    risk_level is derived solely from confidence.
    """
    title: str = ""
    url: str = ""
    snippet: str = ""
    query_source: str = ""
    query_type: str = ""
    store: str = ""

    validation_report: dict[str, ValidationRule] = Field(default_factory=dict)
    validation_score: float = 0.0
    validation_tier: str = "fail"

    extracted_price: Optional[float] = None
    extracted_price_str: Optional[str] = None

    scores: ProductScores = Field(default_factory=ProductScores)
    confidence: float = 0.0     # DETERMINISTIC — never set by LLM
    risk_level: str = "high"    # low | medium | high — derived from confidence

    @classmethod
    def from_validated(
        cls,
        product: ValidatedProduct,
        scores: ProductScores,
    ) -> "ScoredProduct":
        """Construct a ScoredProduct from a ValidatedProduct + computed scores."""
        confidence = (
            scores.signal_score * CONFIDENCE_WEIGHTS["signal"]
            + scores.budget_score * CONFIDENCE_WEIGHTS["budget"]
            + scores.country_score * CONFIDENCE_WEIGHTS["country"]
            + scores.search_quality_score * CONFIDENCE_WEIGHTS["search_quality"]
            + scores.relationship_score * CONFIDENCE_WEIGHTS["relationship"]
        )
        confidence = round(min(max(confidence, 0.0), 1.0), 4)

        if confidence >= 0.75:
            risk_level = "low"
        elif confidence >= 0.50:
            risk_level = "medium"
        else:
            risk_level = "high"

        return cls(
            title=product.title,
            url=product.url,
            snippet=product.snippet,
            query_source=product.query_source,
            query_type=product.query_type,
            store=product.store,
            validation_report=product.validation_report,
            validation_score=product.validation_score,
            validation_tier=product.validation_tier,
            extracted_price=product.extracted_price,
            extracted_price_str=product.extracted_price_str,
            scores=scores,
            confidence=confidence,
            risk_level=risk_level,
        )
